### ISSUE TITLE
脚本运行出错

### ISSUE THREAD

**Issue by BJAny** [XiaoMiku01/miyoubiAuto#17]
签到出现invalid request，点赞分享也没执行，只有看帖是正常的
![image](https://user-images.githubusercontent.com/6690619/182940568-fd5f3a7b-1328-4fc5-8c9c-a509e85124fc.png)
![image](https://user-images.githubusercontent.com/6690619/182940781-e90ee1f0-fe74-4ad6-93d4-637f428a2bf0.png)

**Comment by lie5860** [comment]
同出错

**Comment by BJAny** [comment]
> 同出错

找到问题了，版本号、salt和client_type变了。在Global.py更改此处即可
```
mysVersion = "2.28.1"
salt = "ulInCDohgEs557j0VsPDYnQaaz6KJcv5"  # 米游社2.7.0版本安卓客户端salt值
client_type = "5" 
```
![image](https://user-images.githubusercontent.com/6690619/183253760-48bdc5c8-f589-4077-a362-f56afc995767.png)

**Comment by Womsxd** [comment]
> > 同出错
> 
> 找到问题了，版本号、salt和client_type变了。在Global.py更改此处即可
> 
> ```
> mysVersion = "2.28.1"
> salt = "ulInCDohgEs557j0VsPDYnQaaz6KJcv5"  # 米游社2.7.0版本安卓客户端salt值
> client_type = "5" 
> ```
> 
> ![image](https://user-images.githubusercontent.com/6690619/183253760-48bdc5c8-f589-4077-a362-f56afc995767.png)

你下载最新的源码就行了，最新的源码已经更新到2.34.1了

**Comment by BJAny** [comment]
更新了，谢谢> > > 同出错
> 
> > 
> 
> > 找到问题了，版本号、salt和client_type变了。在Global.py更改此处即可
> 
> > 
> 
> > ```
> 
> > mysVersion = "2.28.1"
> 
> > salt = "ulInCDohgEs557j0VsPDYnQaaz6KJcv5"  # 米游社2.7.0版本安卓客户端salt值
> 
> > client_type = "5" 
> 
> > ```
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/6690619/183253760-48bdc5c8-f589-4077-a362-f56afc995767.png)
> 
> 
> 
> 你下载最新的源码就行了，最新的源码已经更新到2.34.1了，这client_type5模拟的是手机web访问
