### ISSUE TITLE
上传了release的zip包，腾讯云提示创建失败

### ISSUE THREAD

**Issue by bighanhjk** [XiaoMiku01/miyoubiAuto#3]

**Comment by XiaoMiku01** [comment]
已更新，重新下载试试

**Comment by bighanhjk** [comment]
还是提示操作失败
函数创建中...
函数创建失败, 失败原因：
未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by XiaoMiku01** [comment]
刚刚自己试了，成功，你再试试吧

**Comment by zxy328370240** [comment]
上传的包要用up的原包，不要用自己本地提取过cookies的文件夹打包上传，那个只是用来获取变量的。
