### ISSUE TITLE
请问部署方法中第7步执行方法是index.main_handler吗

### ISSUE THREAD

**Issue by zzxgs** [XiaoMiku01/miyoubiAuto#7]
我在腾讯云函数创建失败的提示也是：未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。
还有现在米游社的cookie中好像没有login_ticket了

**Comment by XiaoMiku01** [comment]
https://www.yindan.me/tutorial/genshin-impact-helper.html 看这个项目，此项目已经整合进去了
